services:
  seti:
    container_name: seti-gandaki-web
    build:
      context: .
      dockerfile: Dockerfile
    command: ["daphne", "-b", "0.0.0.0", "-p", "6060", "core.asgi:application"]
    ports:
      - "6060:6060"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6060"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
