# Generated by Django 5.1.3 on 2025-05-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='business_registration',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='phone_number2',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='verification_details',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='verification_document',
        ),
    ]
