# Generated by Django 5.1.3 on 2025-05-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_userbase_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
