# Generated by Django 5.1.3 on 2025-05-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_userbase_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='multi_vendor_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
