# Generated by Django 5.1.3 on 2025-06-12 06:08

import core.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_globalsettings_multi_vendor_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='front_permission_groups',
            field=models.JSONField(blank=True, default=core.utils.functions.default_array, null=True),
        ),
    ]
