# Generated by Django 5.1.3 on 2025-05-28 19:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetrolStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('station_code', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Station code must be 4 digits.')])),
                ('location_details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Petrol Station',
                'verbose_name_plural': 'Petrol Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], max_length=10)),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('vehicle_registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_consumed', models.BooleanField(db_index=True, default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('dispatched_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_tickets_dispatched', to=settings.AUTH_USER_MODEL)),
                ('consumed_by_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_fuel_tickets', to='hrm.petrolstation')),
            ],
            options={
                'verbose_name': 'Fuel Ticket',
                'verbose_name_plural': 'Fuel Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
