# Generated by Django 5.1.3 on 2025-05-28 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
        ('statements', '0011_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Check-in Time')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Check-out Time')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='statements.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date', 'staff__name'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
