# Generated by Django 5.1.3 on 2025-05-29 06:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_attendance'),
        ('statements', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelticket',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='fuelticket',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_tickets', to='statements.vehicle'),
        ),
        migrations.AlterField(
            model_name='petrolstation',
            name='station_code',
            field=models.CharField(blank=True, editable=False, max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Station code must be 4 digits.')]),
        ),
    ]
