# Generated by Django 5.1.3 on 2025-05-29 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_alter_attendance_date_salarydisbursement'),
        ('statements', '0012_staff_enrollment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, help_text='Unique identifier for the ticket (e.g., FT-0001). Auto-generated if blank.', max_length=20, unique=True, verbose_name='Ticket Number')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('other', 'Other')], help_text='Type of meal for which the ticket is valid.', max_length=50, verbose_name='Meal Type')),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the ticket was generated.', verbose_name='Issued At')),
                ('is_used', models.BooleanField(default=False, help_text='Indicates if the ticket has been redeemed.', verbose_name='Is Used')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when the ticket was redeemed.', null=True, verbose_name='Used At')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or comments.', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('issued_by', models.ForeignKey(help_text='The user who generated this food ticket.', on_delete=django.db.models.deletion.PROTECT, related_name='food_tickets_issued', to=settings.AUTH_USER_MODEL, verbose_name='Issued By')),
                ('staff', models.ForeignKey(help_text='The staff member to whom the ticket is issued.', on_delete=django.db.models.deletion.PROTECT, related_name='food_tickets', to='statements.staff', verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Food Ticket',
                'verbose_name_plural': 'Food Tickets',
                'ordering': ['-issued_at'],
            },
        ),
    ]
