# Generated by Django 5.1.3 on 2025-06-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_foodticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodticket',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='foodticket',
            name='used_at',
        ),
        migrations.AddField(
            model_name='fuelticket',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
