# Generated by Django 5.1.3 on 2025-06-13 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_remove_foodticket_is_used_remove_foodticket_used_at_and_more'),
        ('statements', '0028_alter_staff_options_staff_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_user_id', models.CharField(max_length=10, verbose_name='Device User ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('attendance_status', models.CharField(choices=[('0', 'Check In'), ('1', 'Check Out'), ('2', 'Break Out'), ('3', 'Break In')], default='0', max_length=2, verbose_name='Attendance Status')),
                ('verification_method', models.CharField(choices=[('0', 'Password'), ('1', 'Fingerprint'), ('2', 'Card'), ('3', 'Face')], default='1', max_length=2, verbose_name='Verification Method')),
                ('work_code', models.CharField(default='0', max_length=10, verbose_name='Work Code')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is Processed')),
                ('raw_data', models.TextField(blank=True, null=True, verbose_name='Raw Data')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_logs', to='statements.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Device Attendance Log',
                'verbose_name_plural': 'Device Attendance Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
