# Generated by Django 5.1.3 on 2025-06-13 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_deviceattendancelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceattendancelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Device Attendance Log (Deprecated)', 'verbose_name_plural': 'Device Attendance Logs (Deprecated)'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='device_user_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Device User ID'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='raw_device_data',
            field=models.TextField(blank=True, null=True, verbose_name='Raw Device Data'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('DEVICE', 'Device Entry')], default='MANUAL', max_length=10, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('0', 'Password'), ('1', 'Fingerprint'), ('2', 'Card'), ('3', 'Face')], max_length=2, null=True, verbose_name='Verification Method'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Work Code'),
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('event_type', models.CharField(choices=[('0', 'Check In'), ('1', 'Check Out'), ('2', 'Break Out'), ('3', 'Break In')], max_length=2, verbose_name='Event Type')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('DEVICE', 'Device Entry')], default='MANUAL', max_length=10, verbose_name='Source')),
                ('device_user_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Device User ID')),
                ('verification_method', models.CharField(blank=True, choices=[('0', 'Password'), ('1', 'Fingerprint'), ('2', 'Card'), ('3', 'Face')], max_length=2, null=True, verbose_name='Verification Method')),
                ('work_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Work Code')),
                ('raw_data', models.TextField(blank=True, null=True, verbose_name='Raw Data')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hrm.attendance', verbose_name='Attendance')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
