# Generated by Django 5.1.3 on 2025-06-13 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_alter_deviceattendancelog_options_and_more'),
        ('statements', '0028_alter_staff_options_staff_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='deviceattendancelog',
            name='staff',
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out')], default='CHECK_IN', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=django.utils.timezone.localtime, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(choices=[('PASSWORD', 'Password'), ('FINGERPRINT', 'Fingerprint'), ('CARD', 'Card'), ('FACE', 'Face'), ('MANUAL', 'Manual Entry')], default='MANUAL', max_length=20, verbose_name='Verification Method'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['staff', 'date'], name='hrm_attenda_staff_i_842483_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'attendance_type'], name='hrm_attenda_date_51dc33_idx'),
        ),
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
        migrations.DeleteModel(
            name='DeviceAttendanceLog',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='device_user_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='raw_device_data',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='source',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='work_code',
        ),
    ]
