# Generated by Django 5.1.3 on 2025-05-10 15:57

import core.utils.functions
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('purchase_bill_number', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grace_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_and_handling_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_costs_remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_handling_receipt', models.ImageField(blank=True, null=True, upload_to='purchase_bills', validators=[core.utils.functions.limit_size, django.core.validators.validate_image_file_extension])),
                ('status', models.CharField(choices=[('draft', 'draft'), ('approved', 'Approved '), ('shipped', 'Shipped'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('purchase_receipt', models.ImageField(blank=True, null=True, upload_to='purchase_bills', validators=[core.utils.functions.limit_size, django.core.validators.validate_image_file_extension])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statements.business')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('item_description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measurement', models.CharField(blank=True, default='cubic meter', max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('taxable_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percent_applied', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='statements.purchasebill')),
            ],
        ),
    ]
