# Generated by Django 5.1.3 on 2025-05-10 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name'], 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.RemoveField(
            model_name='business',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='business',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='business',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='business',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Business Name'),
        ),
    ]
