# Generated by Django 5.1.3 on 2025-05-11 18:22

import core.utils.functions
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_alter_business_options_remove_business_contact_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('phone_number', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Contact Number')),
                ('verification_document', models.ImageField(blank=True, null=True, upload_to='staff/verifications', validators=[core.utils.functions.limit_size, django.core.validators.validate_image_file_extension])),
                ('pan', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='PAN Number')),
                ('assigned_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='License Plate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['license_plate'],
            },
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='taxable_unit_price',
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='bill_completed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='bill_started_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='assigned_staffs',
            field=models.ManyToManyField(related_name='purchase_bills', to='statements.staff'),
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Purpose of Trip')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes/Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('for_purchase_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statements.purchasebill')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_logs', to='statements.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Trip Log',
                'verbose_name_plural': 'Trip Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='License Plate')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Entry Time')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Exit Time')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Purpose of Visit')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Driver's Name")),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name="Driver's Phone")),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At Record')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At Record')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_gate_passes', to=settings.AUTH_USER_MODEL, verbose_name='Issued By')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_passes', to='statements.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Gate Pass',
                'verbose_name_plural': 'Gate Passes',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='assigned_vehicles',
            field=models.ManyToManyField(related_name='purchase_bills', to='statements.vehicle'),
        ),
    ]
