# Generated by Django 5.1.3 on 2025-05-12 17:05

import core.utils.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_staff_vehicle_remove_purchaseitem_taxable_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles', validators=[core.utils.functions.limit_size, django.core.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='primary_staffs',
            field=models.ManyToManyField(to='statements.staff'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
