# Generated by Django 5.1.3 on 2025-05-12 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0004_vehicle_image_vehicle_note_vehicle_primary_staffs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatepass',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gate Pass', 'verbose_name_plural': 'Gate Passes'},
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='exit_time',
        ),
        migrations.RemoveField(
            model_name='triplog',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='triplog',
            name='gate_pass',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='trip_logs', to='statements.gatepass', verbose_name='Vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Issued At'),
        ),
        migrations.CreateModel(
            name='GatePassMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Exit Time')),
                ('entry_time', models.DateTimeField(blank=True, null=True, verbose_name='Entry Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='statements.gatepass', verbose_name='Gate Pass')),
            ],
            options={
                'verbose_name': 'Gate Pass Movement',
                'verbose_name_plural': 'Gate Pass Movements',
                'ordering': ['gate_pass', '-created_at'],
            },
        ),
    ]
