# Generated by Django 5.1.3 on 2025-05-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0005_alter_gatepass_options_remove_gatepass_entry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
