# Generated by Django 5.1.3 on 2025-05-28 03:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0007_alter_business_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='driver_name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name="Driver's Name"),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name="Driver's Phone"),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='license_plate',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='License Plate'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_pan', models.CharField(blank=True, max_length=255, null=True)),
                ('invoiced_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_on', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('delivery_location', models.TextField(blank=True, null=True)),
                ('delivery_note', models.TextField(blank=True, null=True)),
                ('tracking_code', models.TextField(blank=True, null=True)),
                ('weight_unit', models.CharField(default='cubic_meter', max_length=25)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('additional_charge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('additional_charge_note', models.TextField(blank=True, null=True)),
                ('additional_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('additional_discount_note', models.TextField(blank=True, null=True)),
                ('sub_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('total_taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('serial', models.PositiveIntegerField(default=0)),
                ('fiscal_year_ad', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('fiscal_year_bs', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_invoices', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='statements.business')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_updated_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, default='cubic_meter', max_length=50)),
                ('price_per_item', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=60)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('discount_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=60)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=60)),
                ('is_marked_as_complete', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='statements.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year_change_month_in_bs', models.PositiveIntegerField(default=4)),
                ('fiscal_year_change_day_in_bs', models.PositiveIntegerField(default=1)),
                ('sales_note', models.TextField(default='Thank you for you business.')),
                ('default_quick_invoice_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='statements.business')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
