# Generated by Django 5.1.3 on 2025-05-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0009_expensecategory_expense_expenseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
