# Generated by Django 5.1.3 on 2025-05-28 18:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0010_expense_is_paid_expense_paid_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header', models.CharField(choices=[('credit', 'Credit'), ('fonepay', 'Fonepay'), ('cash', 'Cash'), ('transfer', 'Transfer'), ('card', 'Card')], default='cash', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=60)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payments')),
                ('is_refunded', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='statements.expense')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='statements.invoice')),
                ('purchase_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='statements.purchasebill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
