# Generated by Django 5.1.3 on 2025-05-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Enrollment Date'),
        ),
    ]
