# Generated by Django 5.1.3 on 2025-05-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0012_staff_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Number'),
        ),
    ]
