# Generated by Django 5.1.3 on 2025-05-30 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0013_alter_staff_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplog',
            name='for_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statements.invoice'),
        ),
    ]
