# Generated by Django 5.1.3 on 2025-05-31 02:37

import core.utils.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0014_triplog_for_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='expenses', validators=[core.utils.functions.limit_size, django.core.validators.validate_image_file_extension]),
        ),
    ]
