# Generated by Django 5.1.3 on 2025-05-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_foodticket'),
        ('statements', '0015_expense_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='attached_fuel_tickets',
            field=models.ManyToManyField(related_name='expense_item', to='hrm.fuelticket'),
        ),
    ]
