# Generated by Django 5.1.3 on 2025-05-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0016_expenseitem_attached_fuel_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='assigned_staffs',
            field=models.ManyToManyField(blank=True, related_name='purchase_bills', to='statements.staff'),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='assigned_vehicles',
            field=models.ManyToManyField(blank=True, related_name='purchase_bills', to='statements.vehicle'),
        ),
    ]
