# Generated by Django 5.1.3 on 2025-05-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_foodticket'),
        ('statements', '0017_alter_purchasebill_assigned_staffs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='attached_fuel_tickets',
            field=models.ManyToManyField(blank=True, related_name='expense_item', to='hrm.fuelticket'),
        ),
    ]
