# Generated by Django 5.1.3 on 2025-06-07 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0018_alter_expenseitem_attached_fuel_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination_1000', models.PositiveIntegerField(default=0, help_text='Count of 1000 Rupee notes')),
                ('denomination_500', models.PositiveIntegerField(default=0, help_text='Count of 500 Rupee notes')),
                ('denomination_100', models.PositiveIntegerField(default=0, help_text='Count of 100 Rupee notes')),
                ('denomination_50', models.PositiveIntegerField(default=0, help_text='Count of 50 Rupee notes')),
                ('denomination_20', models.PositiveIntegerField(default=0, help_text='Count of 20 Rupee notes')),
                ('denomination_10', models.PositiveIntegerField(default=0, help_text='Count of 10 Rupee notes')),
                ('denomination_5', models.PositiveIntegerField(default=0, help_text='Count of 5 Rupee notes')),
                ('denomination_2', models.PositiveIntegerField(default=0, help_text='Count of 2 Rupee notes')),
                ('denomination_1', models.PositiveIntegerField(default=0, help_text='Count of 1 Rupee notes')),
            ],
            options={
                'verbose_name': 'Cash Counter',
                'verbose_name_plural': 'Cash Counters',
            },
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='bill_started_from',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
