# Generated by Django 5.1.3 on 2025-06-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0019_cashcounter_alter_purchasebill_bill_started_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcounter',
            name='counter_name',
            field=models.CharField(default='cash counter', help_text='Name of the cash counter', max_length=100),
        ),
    ]
