# Generated by Django 5.1.3 on 2025-06-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0020_cashcounter_counter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCounterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination_1000', models.IntegerField(default=0, help_text='Change in 1000 Rupee notes (positive for added, negative for removed)')),
                ('denomination_500', models.IntegerField(default=0, help_text='Change in 500 Rupee notes')),
                ('denomination_100', models.IntegerField(default=0, help_text='Change in 100 Rupee notes')),
                ('denomination_50', models.IntegerField(default=0, help_text='Change in 50 Rupee notes')),
                ('denomination_20', models.IntegerField(default=0, help_text='Change in 20 Rupee notes')),
                ('denomination_10', models.IntegerField(default=0, help_text='Change in 10 Rupee notes')),
                ('denomination_5', models.IntegerField(default=0, help_text='Change in 5 Rupee notes')),
                ('denomination_2', models.IntegerField(default=0, help_text='Change in 2 Rupee notes')),
                ('denomination_1', models.IntegerField(default=0, help_text='Change in 1 Rupee notes')),
                ('pre_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount in cash counter before this log was applied.', max_digits=10, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount in cash counter after this log was applied.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_applied', models.BooleanField(default=False, help_text='Indicates if the changes in this log have been applied to the cash counter.')),
                ('cash_counter', models.ForeignKey(help_text='The cash counter being updated by this log.', on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='statements.cashcounter')),
            ],
            options={
                'verbose_name': 'Cash Counter Log',
                'verbose_name_plural': 'Cash Counter Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
