# Generated by Django 5.1.3 on 2025-06-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0021_cashcounterlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcounterlog',
            name='remarks',
            field=models.TextField(blank=True, help_text='Reason or purpose for this cash counter change.'),
        ),
    ]
