# Generated by Django 5.1.3 on 2025-06-08 10:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0022_cashcounterlog_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='due_expense_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=60, verbose_name='Due Expense Amount'),
        ),
        migrations.AddField(
            model_name='business',
            name='due_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=60, verbose_name='Due Invoice Amount'),
        ),
        migrations.AddField(
            model_name='business',
            name='due_purchase_bill_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=60, verbose_name='Due Purchase Bill Amount'),
        ),
        migrations.AddField(
            model_name='business',
            name='total_expense_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=60, verbose_name='Total Expense Amount'),
        ),
        migrations.AddField(
            model_name='business',
            name='total_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=60, verbose_name='Total Invoice Amount'),
        ),
        migrations.AddField(
            model_name='business',
            name='total_purchase_bill_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=60, verbose_name='Total Purchase Bill Amount'),
        ),
    ]
