# Generated by Django 5.1.3 on 2025-06-09 19:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0023_business_due_expense_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=60, verbose_name='Current Amount')),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.RemoveField(
            model_name='business',
            name='due_expense_amount',
        ),
        migrations.RemoveField(
            model_name='business',
            name='due_invoice_amount',
        ),
        migrations.RemoveField(
            model_name='business',
            name='due_purchase_bill_amount',
        ),
        migrations.RemoveField(
            model_name='business',
            name='total_expense_amount',
        ),
        migrations.RemoveField(
            model_name='business',
            name='total_invoice_amount',
        ),
        migrations.RemoveField(
            model_name='business',
            name='total_purchase_bill_amount',
        ),
        migrations.AddField(
            model_name='business',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=60, verbose_name='Current Amount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='action',
            field=models.CharField(choices=[('withdraw', 'Withdraw'), ('deposit', 'Deposit')], default='deposit', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='related_business',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='statements.business'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='header',
            field=models.CharField(choices=[('from_business_credit', 'From Business Credit'), ('fonepay', 'Fonepay'), ('cash', 'Cash'), ('transfer', 'Transfer'), ('card', 'Card')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='related_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='statements.account'),
        ),
        migrations.CreateModel(
            name='BusinessCreditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=60)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='business_credit_receipts')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_logs', to='statements.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
