# Generated by Django 5.1.3 on 2025-06-10 03:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0024_account_remove_business_due_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=60, verbose_name='Current Amount'),
        ),
        migrations.AlterField(
            model_name='business',
            name='registration_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Registration Number'),
        ),
    ]
