# Generated by Django 5.1.3 on 2025-06-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0025_alter_business_current_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='header',
            field=models.CharField(choices=[('business_credit', 'Business Credit'), ('fonepay', 'Fonepay'), ('cash', 'Cash'), ('transfer', 'Transfer'), ('card', 'Card')], default='cash', max_length=20),
        ),
    ]
