# Generated by Django 5.1.3 on 2025-06-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0026_alter_payment_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
