# Generated by Django 5.1.3 on 2025-06-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0027_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AddField(
            model_name='staff',
            name='device_id',
            field=models.CharField(blank=True, help_text='ZKTeco device user ID for attendance tracking', max_length=10, null=True, unique=True, verbose_name='Device User ID'),
        ),
    ]
