# Generated by Django 5.1.3 on 2025-06-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0028_alter_staff_options_staff_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_vendor',
            field=models.BooleanField(default=True),
        ),
    ]
