# Generated by Django 5.1.3 on 2025-06-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0029_business_is_customer_business_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_for_header',
            field=models.CharField(choices=[('fonepay', 'Fonepay'), ('cash', 'Cash'), ('transfer', 'Transfer'), ('card', 'Card')], default='cash', max_length=20),
        ),
    ]
