# Generated by Django 5.1.3 on 2025-07-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0031_update_invoice_item_quantity_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='is_marked_as_complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
