[uwsgi]
uid = ubuntu
gid = ubuntu
base_dir = /home/%(uid)/wholesale-dai
module_dir = /home/%(uid)/wholesale-dai/src
virtualenv = /home/%(uid)/wholesale-dai/.venv
chdir = %(module_dir)

module = core.wsgi:application

master = true
processes = 2
post-buffering = 204800

thunder-lock = true

socket = %(base_dir)/uwsgi.sock
chmod-socket = 666
socket-timeout = 300
reload-mercy = 8
reload-on-as = 512
harakiri = 50
max-requests = 5000
vacuum = true
disable-logging = true
logto = %(base_dir)/uwsgi.log
log-maxsize = 20971520
touch-reload = %(base_dir)/src/core/
max-worker-lifetime = 300